version: 4
jobs:
        main:
            requires: [~commit]
            sourcePaths: ["screwdriver.yaml"]
            image: python:3.6
            steps:
                - export: export GREETING="Hello, world! welcome to screwdriver"
                - hello: echo $GREETING
